### ISSUE TITLE
extract_tables error: java.lang.NullPointerException

### ISSUE THREAD

**Issue by rhz** [ropensci/tabulizer#69]
When using extract_table on pdf files
http://www.comunidadesagricolas.cl/wp-content/uploads/nominas/2010/elqui/estero_derecho.pdf
http://www.comunidadesagricolas.cl/wp-content/uploads/nominas/2010/limari/rinconada_de_punitaqui.pdf
I get the following error
```
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  java.lang.NullPointerException
```

However, when using the last version of [tabula](https://github.com/tabulapdf/tabula-java/releases/tag/v1.0.1) (v1.0.1) and running it like
```
java -jar tabula-1.0.1-jar-with-dependencies.jar estero_derecho.pdf -o e.csv
```
it works without any issues and the generated file `e.csv` contains the table.

I should add that tabulizer has no problems with the other pdf files in http://www.comunidadesagricolas.cl/wp-content/uploads/nominas/

**Comment by tpaskhalis** [comment]
`tabulizer` has recently been updated to use the latest version of `Tabula` (1.0.1), so the issue should be resolved. Please, let me know if there are still any problems.

**Comment by ekesawi** [comment]
I am still having a problem with the same error when using locate_areas to extract tables. It works for 1 or 2 tables from a small pdf files, but does't work for others. I uploaded the latest tabulizer version. I tested the code on the articles (files) below where i wanted to extract several tables from each article

https://pdfs.semanticscholar.org/50a4/2b8146f08161b1036457fe0d241b6b898974.pdf
https://pdfs.semanticscholar.org/50a4/2b8146f08161b1036457fe0d241b6b898974.pdf   

Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  java.lang.NullPointerException

> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.2.0     miniUI_0.1.1.1  tabulizer_0.2.2 rJava_0.9-10   

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.18        png_0.1-7           digest_0.6.16       later_0.7.5         mime_0.5           
 [6] R6_2.2.2            jsonlite_1.5        xtable_1.8-3        magrittr_1.5        rlang_0.2.2        
[11] promises_1.0.1      tabulizerjars_1.0.1 tools_3.5.2         httpuv_1.4.5.1      yaml_2.2.0         
[16] compiler_3.5.2      htmltools_0.3.6
